In [5]:
import numpy as np

# Our movie-user rating matrix
M = np.array([
    [5, 4, 1, 2],
    [1, 2, 5, 4],
    [4, 5, 1, 2],
    [2, 1, 5, 4]
], dtype=float)

# Run SVD
U, S, Vt = np.linalg.svd(M)

print("Singular values (S):")
print(np.round(S, 2))

print("\nShape of U:", U.shape)
print("Shape of S:", S.shape)
print("Shape of Vt:", Vt.shape)

Singular values (S):
[12.    6.16  1.41  0.  ]

Shape of U: (4, 4)
Shape of S: (4,)
Shape of Vt: (4, 4)


In [7]:
def reconstruct(U, S, Vt, k):
    # Keep only top-k singular values
    U_k  = U[:, :k]           # first k columns of U
    S_k  = np.diag(S[:k])     # k×k diagonal matrix
    Vt_k = Vt[:k, :]          # first k rows of Vt
    return U_k @ S_k @ Vt_k

print("Original matrix:")
print(np.round(M, 1))

print("\nReconstructed with k=1:")
print(np.round(reconstruct(U, S, Vt, 1), 1))

print("\nReconstructed with k=2:")
print(np.round(reconstruct(U, S, Vt, 2), 1))

print("\nReconstructed with k=4:")
print(np.round(reconstruct(U, S, Vt,4), 1))

Original matrix:
[[5. 4. 1. 2.]
 [1. 2. 5. 4.]
 [4. 5. 1. 2.]
 [2. 1. 5. 4.]]

Reconstructed with k=1:
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]

Reconstructed with k=2:
[[4.5 4.5 1.  2. ]
 [1.5 1.5 5.  4. ]
 [4.5 4.5 1.  2. ]
 [1.5 1.5 5.  4. ]]

Reconstructed with k=4:
[[5. 4. 1. 2.]
 [1. 2. 5. 4.]
 [4. 5. 1. 2.]
 [2. 1. 5. 4.]]


In [7]:
import os
import shutil

base = r"C:\Users\kunjs\OneDrive\Prekki"
dump = os.path.join(base, "THE DUMP")
review = os.path.join(base, "_REVIEW")
os.makedirs(review, exist_ok=True)

# Build a set of all filenames in THE DUMP (case-insensitive)
dump_files = set()
for fname in os.listdir(dump):
    if os.path.isfile(os.path.join(dump, fname)):
        dump_files.add(fname.lower())

moved = []

# Walk all other folders recursively
for folder in os.listdir(base):
    folder_path = os.path.join(base, folder)
    if folder in ("THE DUMP", "_REVIEW") or not os.path.isdir(folder_path):
        continue

    for root, dirs, files in os.walk(folder_path):
        for fname in files:
            if fname.lower() in dump_files:
                src = os.path.join(root, fname)
                dst = os.path.join(review, fname)
                # Avoid overwriting if two folders had the same duplicate
                if os.path.exists(dst):
                    name, ext = os.path.splitext(fname)
                    dst = os.path.join(review, f"{name}_conflict{ext}")
                shutil.move(src, dst)
                moved.append(src)

print(f"Moved {len(moved)} duplicates to _REVIEW:")
for f in moved:
    print(" ", f)

Moved 0 duplicates to _REVIEW:
