In [5]:
import numpy as np

# Our movie-user rating matrix
M = np.array([
    [5, 4, 1, 2],
    [1, 2, 5, 4],
    [4, 5, 1, 2],
    [2, 1, 5, 4]
], dtype=float)

# Run SVD
U, S, Vt = np.linalg.svd(M)

print("Singular values (S):")
print(np.round(S, 2))

print("\nShape of U:", U.shape)
print("Shape of S:", S.shape)
print("Shape of Vt:", Vt.shape)

Singular values (S):
[12.    6.16  1.41  0.  ]

Shape of U: (4, 4)
Shape of S: (4,)
Shape of Vt: (4, 4)


In [7]:
def reconstruct(U, S, Vt, k):
    # Keep only top-k singular values
    U_k  = U[:, :k]           # first k columns of U
    S_k  = np.diag(S[:k])     # k×k diagonal matrix
    Vt_k = Vt[:k, :]          # first k rows of Vt
    return U_k @ S_k @ Vt_k

print("Original matrix:")
print(np.round(M, 1))

print("\nReconstructed with k=1:")
print(np.round(reconstruct(U, S, Vt, 1), 1))

print("\nReconstructed with k=2:")
print(np.round(reconstruct(U, S, Vt, 2), 1))

print("\nReconstructed with k=4:")
print(np.round(reconstruct(U, S, Vt,4), 1))

Original matrix:
[[5. 4. 1. 2.]
 [1. 2. 5. 4.]
 [4. 5. 1. 2.]
 [2. 1. 5. 4.]]

Reconstructed with k=1:
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]

Reconstructed with k=2:
[[4.5 4.5 1.  2. ]
 [1.5 1.5 5.  4. ]
 [4.5 4.5 1.  2. ]
 [1.5 1.5 5.  4. ]]

Reconstructed with k=4:
[[5. 4. 1. 2.]
 [1. 2. 5. 4.]
 [4. 5. 1. 2.]
 [2. 1. 5. 4.]]
